version: '2'

services:
  stubby:
    container_name: stubby
    image: kurioscurious/docker-stubby
    ports:
      - 53/udp
    restart: unless-stopped
    networks:
      dnsnet:
        ipv4_address: ${STUBBY_IP}
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53/udp
      - 80/tcp
      - 443/tcp
    environment:
      TZ: '${TZ}'
      WEBPASSWORD: '${PIHOLE_WEBPASS}'
      ServerIP: ${PIHOLE_IP}
      VIRTUAL_HOST: '${PIHOLE_VHOST}'
      IPv6: 'False'
      DNS1: ${STUBBY_IP}
      DNS2: 'no'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - ${STUBBY_IP}
    networks:
      dnsnet:
        ipv4_address: ${PIHOLE_IP}
    restart: unless-stopped

networks:
  dnsnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: '${SUBNET}'
